### ISSUE TITLE
xiao_esp32c3 bluepad not show anything in serial monitor after reset

### ISSUE THREAD

**Issue by attaponaerospace** [ricardoquesada/bluepad32#101]
I tried to use xiao esp32c3 bluepad version to run example : controller. I had successful uploaded the code. I started serial monitor in arduino ide , then pressed reset button and nothing happened.

Even I also try such a simple code like

#include < bluepad32.h>
ControllerPtr myControllers[BP32_MAX_GAMEPADS];

void setup() {
      Serial.begin(115200);
     Serial.printf("Firmware: %s\n", BP32.firmwareVersion());
}

void loop(){
}

Also nothing printing out

**Comment by ricardoquesada** [comment]
try this:
https://github.com/ricardoquesada/bluepad32/issues/65#issuecomment-1987046804

if it doesn't help, please reopen the ticket.
