### ISSUE TITLE
relay gamepad using websocket or serial to PC

### ISSUE THREAD

**Issue by rvxfahim** [ricardoquesada/bluepad32#110]
I was wondering whether I could connect to a controller and essentially pass this data over wifi websocket or serial to a python client in pc and map that data to a vjoy controller, this would make the esp32 as a gamepad receiver for PC without any bluetooth dongle. Is it a viable solution ?

**Comment by ricardoquesada** [comment]
it should be possible. you can even do it via USB if you use a PicoW .
ESP32-S3 works as well but with a limited support of gamepads
