### ISSUE TITLE
[Bug]: Ps4 Controller dont connect

### ISSUE THREAD

**Issue by SkyDumpper** [ricardoquesada/bluepad32#111]
### What happened?

Hello! First of all, thank you very much for the work it took you to make this library. I have a problem and that is that my PS4 controller does not connect to my Esp32, I am using a Haltec Wifi kit 32 v3 module. The "Controller" example code is compiled and uploaded without problems to the esp32, but the controller never connects either by first pressing the share button and then the PS button, or by pressing only the PS button. This is what I get via serial:

`ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce3808,len:0x4bc
load:0x403c9700,len:0xbd8
load:0x403cc700,len:0x2a0c
entry 0x403c98d0
Bluepad32 (C) 2016-2024 Ricardo Quesada and contributors.
Version: v4.1.0
BTstack: Copyright (C) 2017 BlueKitchen GmbH.
BTstack up and running at 48:27:E2:EM⸮Firmware: Bluepad32 for Arduino v4.1.0
BD Addr: 48:27:E2:E5:AC:81`

### Bluepad32 Version

latest from develop branch

### Bluepad32 version custom

Example: Using Git develop branch commit hash #xxxxxxx

### Bluepad32 Platform

Arduino IDE

### Platform version

Arduino IDE 1.8.16

### Controller

PS4 Dual shock

### Microcontroller

ESP32-S3

### Microcontroller board

ESP32-S3 Heltec Wifi Kit 32 V3 

https://heltec.org/project/wifi-kit32-v3/

### OS

Windows

**Comment by ricardoquesada** [comment]
ESP32-S3 (BLE only) is not compatible with DualShock4 (BT Classic).

See: https://bluepad32.readthedocs.io/en/latest/supported_gamepads/#bluetooth-gamepads-and-their-protocol

**Comment by SkyDumpper** [comment]
Hola Ricardo, por el nombre y apellidos supongo que hablas español.. una
pregunta si no es mucha molestia.. conoces algun modulo que tenga pantalla
oled integrada y sea compatible con el mando de ps4? muchas gracias.

**Comment by ricardoquesada** [comment]
creo que la que esta en este thread funciona:

https://discord.com/channels/775177861665521725/1125196127470358668/threads/1264169811076841565
