### ISSUE TITLE
[Bug]: Arduino Nano ESP32 is responding, but DualSense can't connect to the board.

### ISSUE THREAD

**Issue by HenryWang001** [ricardoquesada/bluepad32#115]
### What happened?

A bug happened!

### Bluepad32 Version

4.0-beta1

### Bluepad32 version custom

Firmware: Bluepad32 for Arduino v4.1.0

### Bluepad32 Platform

Arduino IDE

### Platform version

Arduino IDE 2.3.2

### Controller

DualSense is waiting to connect, but nothing happened.

### Microcontroller

ESP32-S3

### Microcontroller board

Arduino Nano ESP32

### OS

macOS

### Relevant log output

```shell
Bluepad32 (C) 2016-2024 Ricardo Quesada and contributors.
Version: v4.1.0
BTstack: Copyright (C) 2017 BlueKitchen GmbH.
BTstack up and running at 34:85:18:7B:56:D1
Firmware: Bluepad32 for Arduino v4.1.0
BD Addr: 34:85:18:7B:56:D1
```

### Relevant sketch

```shell
Using the Receive_Data.ino file offered.
```

**Comment by ricardoquesada** [comment]
Arduino Nano ESP32 is an ESP32-S3 and does not support the BR/EDR, used by DualSense.

See: https://bluepad32.readthedocs.io/en/latest/supported_gamepads/#bluetooth-gamepads-and-their-protocol
