### ISSUE TITLE
[Feature Request] Add ESP32-BLE-Gamepad support

### ISSUE THREAD

**Issue by LeeNX** [ricardoquesada/bluepad32#117]
More like a Feature Confirmed, mostly. 

I was able to connect to ```bluepad32``` running on an ESP32-Dev board, with an ESP32-C3 running ```TestAll.ino``` sketch from [ESP32-BLE-Gamepad](https://github.com/lemmingDev/ESP32-BLE-Gamepad)

bluepad32 reported the following on re-connect
```
Controller model: Android, VID=0x02e5, PID=0xcdab
idx=0, dpad: 0x00, buttons: 0x0000, axis L: -512, -512, axis R: -512, -512, brake:    0, throttle:    0, misc: 0x02, gyro x:     0 y:     0 z:     0, accel x:     0 y:     0 z:     0
idx=0, dpad: 0x00, buttons: 0x0000, axis L: -512, -512, axis R: -512, -512, brake:    0, throttle:    0, misc: 0x04, gyro x:     0 y:     0 z:     0, accel x:     0 y:     0 z:     0
```
I can confirm changes in the attrib as per the TestAll sketch. I was thinking it might be possible to add the battery status in the serial reporting.  
 
Might be worth adding a note to the ```Android``` section about making your own gamepad that would be supported.  
  
I don't have any other ESP32 device, so I can't test a pure BLE setup, but that is something I plan too do.

**Comment by ricardoquesada** [comment]
Thanks for testing it.

regarding the doc, would you like to add the info yourself in the doc ?
This file: https://github.com/ricardoquesada/bluepad32/blob/main/docs/supported_gamepads.md
(use `develop` branch).

Reporting the battery, yes, that is pending for BLE devices.

**Comment by LeeNX** [comment]
I can try over the weekend. See if I can make something that is acceptable.  
  
Thanks

**Comment by LeeNX** [comment]
Thanks @ricardoquesada , I was not sure if more info or details to the ```TestAll.ino``` sketch was worth putting into the docs, but I think we can close this as it's merged.  
  
If you think anything else is worth adding, let me know.

**Comment by ricardoquesada** [comment]
Thanks. I simplified the doc a bit.
