### ISSUE TITLE
[uni_hid_device_disconnect: Unknown GAP connection type: 0] Error upon attempting to connect more than one controller.

### ISSUE THREAD

**Issue by AbelHooked** [ricardoquesada/bluepad32#126]
I'm using the latest version of Bluepad32 on a ESP32-WROOM-32D, and I am unable to connect more than one controller. Right now I have a DualSense and two Joycons to experiment with, and any combination of those controllers fails to connect.

The error message I get is:
`uni_hid_device_disconnect: Unknown GAP connection type: 0`

Is this a known issue? How can I fix this?

Thanks in advance.

**Comment by ricardoquesada** [comment]
good to know that you find the fix
