### ISSUE TITLE
Type in Arduino build description?

### ISSUE THREAD

**Issue by mwedmark** [ricardoquesada/bluepad32#17]
I've just tried building the Arduino project according to the desciption in page:
https://github.com/ricardoquesada/bluepad32/blob/main/docs/plat_arduino.md

It did not work for me exactly like described. 
Maybe I'm missing some alias or something installed but:

It seems that the:
"idf.py make"

Should possibly be:
"idf.py build"

**Comment by ricardoquesada** [comment]
thanks. fixed!
