### ISSUE TITLE
Xbox One X Controller firmware version 5.13.3143.0

### ISSUE THREAD

**Issue by danko79** [ricardoquesada/bluepad32#24]
Hi, i have a Xbox One X controller 1708 model with the last update firmware 5.13.3143.0, is there any chance updating the bluepad32 firmware?

**Comment by ricardoquesada** [comment]
I wasn't aware that a new FW was released for the controller... I'll take a look at it.

**Comment by ricardoquesada** [comment]
It seems that FW 5.13.3143.0 migrated from Bluetooth Classic to BLE only.

So, in order to support it I have to add BLE support.... which was already in the todo list

**Comment by ricardoquesada** [comment]
More info about 5.13.3143.0 , and how to revert to 4.8 (as a temporary solution):

https://www.reddit.com/r/xboxinsiders/comments/ta7kib/xbox_one_controller_firmware_5133143_available/

**Comment by danko79** [comment]
Works with downgrade the firmware.
