### ISSUE TITLE
[Feature Request] analogWrite for RGB LED

### ISSUE THREAD

**Issue by JMyrng** [ricardoquesada/bluepad32#27]
First of all, awesome library.

Now to my request: 
Board MKR1010 with Bluepad32 for NINA v3.5.1

Is it possible to add analogWrite to the Bluepad32 class? Or is that a limitation in fw?

Best regards.

**Comment by ricardoquesada** [comment]
just to understand, you want to perform an `analogWrite` in the ESP32, correct?

**Comment by JMyrng** [comment]
Yes, with original NINA fw it is possible to set these pins with `analogWrite`.

**Comment by ricardoquesada** [comment]
got it.
