### ISSUE TITLE
Platformio and BluePad32

### ISSUE THREAD

**Issue by PacciK** [ricardoquesada/bluepad32#35]
How can one compile successfully the adruino IDE given example "controller" on Platform.io ?

**Comment by ricardoquesada** [comment]
I'm not sure since I don't use Platform.io.

My guess is that it should be similar to regular ESP32 Arduino (???).
Perhaps you need to specify somewhere from where to download thre ESP32-bluepad32 core (???)

**Comment by PacciK** [comment]
Hi Ricardo. Thanks for your reply. I am not so experienced either with Platform.io Hence my request for help.
I am now trying to experiment using Arduino IDE 2.1.0 to bypass having to use Platform.io

What I am attempting is to combine/modify [this project](https://github.com/TheDIYGuy999/Rc_Engine_Sound_ESP32) to work with a PS4 controller.
I had some success using t[his other PS4 library](https://github.com/aed3/PS4-esp32)
However, AED3's PS4 library simply does NOT work with 2013 (CUH-ZCT1) and is sometimes temperamental with 2016 (CUH-ZCT2) controllers.

Meanwhile your library works like a dream on both ZCT1 and ZCT2, and your pairing method makes it simple to use with different Remote control models.

The issues I am wishing to resolve:
 [This project](https://github.com/TheDIYGuy999/Rc_Engine_Sound_ESP32) explicitly needs to use Espressif-ESP32 Board Definitions **<1.06** or **<1.05**.  It simply will not work with V2.x
If I compile using any ESP32's from your Board Defs, the RC_engineSound Project will not work due to requiring 1.06. 
If I use v1.06, the other project works, but Your Library will not work. Presumably because of your specific Bluetooth functions and the renames.
I am close to giving up :/

**Comment by ricardoquesada** [comment]
mmm... sorry, I cannot help.

I guess your best option is to ask RC_Engine_Sound project to update their library.

Bluepad32 only works with ESP32 Arduino Core 2.x.

**Comment by PacciK** [comment]
Dear Ricardo, thanks for your reply. Of course I understand your point perfectly.
Please close this post. You can even delete it if you wish.
Thanks once again for your very versatile project.
