### ISSUE TITLE
[Bug]:   thumbR button not working

### ISSUE THREAD

**Issue by davidxgames** [ricardoquesada/bluepad32#38]
### What happened?

A bug happened! thumbR button not working
 working:
```
            if (myGamepad->l2()) {
                myGamepad->setRumble(0xc0 /* force */, 0xc0 /* duration */);
            }
```
           not working:
```
            if (myGamepad->thumbR()) {
                myGamepad->setRumble(0xc0 /* force */, 0xc0 /* duration */);
            }

```

### Bluepad32 Version

3.7.2 (latest stable)

### Bluepad32 version custom

Example: Using Git develop branch commit hash #xxxxxxx

### Bluepad32 Platform

Arduino ESP-IDF

### Platform version

ESP-IDF v4.4.4

### ESP32 chip

ESP32

### ESP32 board

ESP32 WROOM DevKit 

### OS

Windows

**Comment by ricardoquesada** [comment]
which gamepad are you using?

**Comment by davidxgames** [comment]
> which gamepad are you using?

DS5

**Comment by davidxgames** [comment]
The button works in serial shows this, buttons: 0x0200, but it does not activate the rumble.

**Comment by ricardoquesada** [comment]
so the bug is that rumble doesn't work on DualSense ?

**Comment by davidxgames** [comment]
I already saw the problem, when the rumble function is like this it does not work

`            if (rumble) {
                if (myGamepad->r1()) {
                    digitalWrite(RPin, LOW);
                    myGamepad->setRumble(0xc0 /* force */, 0xc0 /* duration */);
                } else {
                    digitalWrite(RPin, HIGH);
                }
            }`

**Comment by davidxgames** [comment]
> so the bug is that rumble doesn't work on DualSense ?

A thousand apologies, I already checked and the problem is how I am writing the code, thanks for answering, sorry for the wasted time.
