### ISSUE TITLE
When disconnect is called on the second controller, the first controller disconnect.(PS4 controller esp32WROVER-IE)

### ISSUE THREAD

**Issue by 8Kei** [ricardoquesada/bluepad32#50]
Hello sir , I am tried the sample as is, When the disconnect() function is called on the second ps4 controller, only the first ps4 controller will be disconnected.

(I'm using 'Controller.ino' from example in Arduino IDE . Upload Controller.ino to ESP32.)

**Comment by 8Kei** [comment]
Platform:Arduino IDE for ESP32 modules
ESP32 Module:esp32 wrover ie
Controller:ps4 controller (MODEL CUH-ZCT2J)
Sketch :https://gist.github.com/8Kei/555e1bcd2e3acb1382e58c518f0c3ec3
OS:windows 11
Debug log(Serial monitor):
Pressing a button on the second controller will also display this statement.

22:24:02.287 -> CALLBACK: Gamepad is disconnected from index=0
22:24:02.287 -> CALLBACK: Gamepad is disconnected from index=1

**Comment by ricardoquesada** [comment]
what Bluepad32 version?

**Comment by 8Kei** [comment]
version 3.9.0
![スクリーンショット 2023-10-29 233350](https://github.com/ricardoquesada/bluepad32/assets/94771114/a4444fcf-a3e0-4a9a-b4fb-54cfedb1d068)

**Comment by ricardoquesada** [comment]
v3.9.0 and newer have "virtual devices" support. Meaning that controllers like the DualShock4 and DualSense will have two "devices" when one is connected.
The first one is the gamepad.
The second one is a mouse... you can use touchpad as the mouse.
If you disconnect the real device (gamepad), the mouse will be disconnected as well

**Comment by 8Kei** [comment]
I'm so Sorry, I typed that out and didn't realize how vague it ended up being.
When a real second controller is connected, the connection of the first controller is disconnected.

**Comment by ricardoquesada** [comment]
I really don't understand the problem...

add more details please... otherwise I wouldn't know how to help you.

**Comment by 8Kei** [comment]
When I press the button on the real second controller and try to disconnect by calling disconnect as in the source code, only those two lines are called back and displayed.

**Comment by 8Kei** [comment]
I want to disconnect only the second connected controller with different buttons assigned. However, when I press the button on the second controller, the first controller is disconnected and I do not know how to disconnect the second controller.

**Comment by ricardoquesada** [comment]
got it. you can use the allowlist API.

https://github.com/ricardoquesada/bluepad32/blob/main/src/components/bluepad32/include/uni_bt_allowlist.h

**Comment by microbmen** [comment]
I am seeing this bug too. 

if I call ctl->disconnect(); on any index ... i.e. index 1 ... only the controller on index 0 is disconnected.  

I'm on Bluepad32  3.10.2


to reproduce, use your example .ino ...  make ctl->y() perform ctl->disconnect()  ... connect 2 or more controllers... pressing ctl->y() on any of the controllers only disconnects controller index 0;

**Comment by ricardoquesada** [comment]
if I have the time, I'll release 4.0-beta0 this weekend, which will have the bug fixed

**Comment by ricardoquesada** [comment]
just to clarify, the bug appears only on the NINA platform... if you are using "Arduino IDE" + regular ESP32 boards, then it shouldn't happen (I guess).

could you confirm the board that you are using ?

**Comment by ricardoquesada** [comment]
got it. I'll double check it on the non-nina then

**Comment by ricardoquesada** [comment]
I confirm that this was fixed on `develop` branch as well.

**Comment by microbmen** [comment]
Yes fixed in 4.0. Thx.
