### ISSUE TITLE
DS4 setColorLED

### ISSUE THREAD

**Issue by JuPrgn** [ricardoquesada/bluepad32#53]
Using Bluepad example : Controller and changing setColorLed values

I don't see differences between values from 90 to 255, maybe it's a percentage and the value should be 0 to 100? The example uses 255 by default which leads me to believe that there is a scaling error?

Bluepad32 version 
esp32_bluepad 3.10.2

Bluepad32 Platform
Arduino IDE 2.2.1

```
void processGamepad(ControllerPtr ctl) {
    // There are different ways to query whether a button is pressed.
    // By query each button individually:
    //  a(), b(), x(), y(), l1(), etc...
    if (ctl->a()) {
        static int colorIdx = 0;
        ctl->setColorLED(colorIdx, 0, 0);
        colorIdx+=10;
        if(colorIdx > 200)
          colorIdx = 0;
```

**Comment by ricardoquesada** [comment]
Are you using Genuine DS4 controllers ?

**Comment by JuPrgn** [comment]
You are right this is working fine with genuine controller, my bad I assumed they were similar. 

I am using these controllers : 
- clone (Data frog CFKJ-P02-DEC-16) (issue opened for this one)
- official (CUH-ZCT1) (working as expected)

On the clone 0, 0, 0 value turn on white color and value change are visible from 0 to almost 90.
On genuine controller 0, 0, 0 turn off leds and value change from 0 to 255.
