### ISSUE TITLE
[Bug]: Pairing/Connection issues at startup

### ISSUE THREAD

**Issue by sideprojectslab** [ricardoquesada/bluepad32#55]
### What happened?

Please see my Blue-64 project to reproduce the issue https://github.com/sideprojectslab/blue-64 (re-enable console output). Reproducing this issue can be done on a bare ESP32 wroom or wrover devkit without need for any additional components.

More often than not, once the board boots, the controller does not pair or does not connect. The console output shows that the bluepad32 core is stuck in a loop.

Controllers used:
- 8BitDo SN30 Pro Bluetooth Gamepad
- Xbox Wireless Controller 1708

### Bluepad32 Version

3.8.3

### Bluepad32 version custom

Example: Using Git develop branch commit hash 85100a4ec6a43e451fa74049049a02ad53025042

### Bluepad32 Platform

Other

### Platform version

Blue-64

### Controller

- 8BitDo SN30 Pro Bluetooth Gamepad
- Xbox Wireless Controller 1078

### ESP32 chip

ESP32

### ESP32 board

ESP32-wroom-32E (ESP32_DevKitc_V4)

### OS

Windows

**Comment by ricardoquesada** [comment]
please attach the logs that you see.
and the Xbox FW that you are using

**Comment by sideprojectslab** [comment]
Hello, My apologies, I had to shelve the project for a while. Here are the logs your requested for both failure to connect (when already paired) and failure to pair. I must admit that is seems to be related to the amount of other bluetooth devices active in the surroundings, though it's just 3 or 4 max in my case.

How do I find out the "Xbox firmware" that you are requesting?
[logs_connect.txt](https://github.com/ricardoquesada/bluepad32/files/13851431/logs_connect.txt)
[logs_pair.txt](https://github.com/ricardoquesada/bluepad32/files/13851432/logs_pair.txt)

**Comment by ricardoquesada** [comment]
From `logs_pair.txt` you have `Firmware Revision: 5.15.3168.0`.

The latest version is 5.17 (IIRC)... try to upgrade it if you can. You will need a Windows machine, or an Xbox console.

But you mentioned that you are using Bluepad32 v3.8.3. In v3.9.0 Xbox reliability was improved and in v3.10, some other Xbox bug were fixed. Please upgrade to latest Bluepad32 version.

**Comment by sideprojectslab** [comment]
Ok, thanks for the info, I'll upgrade everything as you suggested and come back to you. I think we can close this issue for the time being

**Comment by sideprojectslab** [comment]
For now I'll try your suggestions and see what happens
