### ISSUE TITLE
The ESP32 WROOM32 development board is getting hot.

### ISSUE THREAD

**Issue by gInnaro** [ricardoquesada/bluepad32#57]
After compiling the code in Arduino IDE, the ESP32 starts to heat up significantly. With prolonged use of the board, the power circuit on the ESP32 burns out, specifically the +3.3 and GND tracks short circuit

**Comment by ricardoquesada** [comment]
doesn't look like a Bluepad32 bug.

Perhaps a faulty dev board... try to get another one.
