### ISSUE TITLE
[Bug]: `uni_hid_device_get_idx_for_instance()` reports index 0 for all devices

### ISSUE THREAD

**Issue by juan518munoz** [ricardoquesada/bluepad32#62]
### What happened?

Running example program, inside `static void my_platform_on_controller_data(uni_hid_device_t* d, uni_controller_t* ctl)` I've set a variable to get the index of each connected gamepad, all report to zero.

```c
static void my_platform_on_controller_data(uni_hid_device_t* d, uni_controller_t* ctl) {
    int id = uni_hid_device_get_idx_for_instance(d);
    logi("id %d ", idx);
    ...
```

### Bluepad32 Version

Latest

### Bluepad32 version custom

Develop branch

### Bluepad32 Platform

Other

### Platform version

Pico W

### Controller

Joycons, Xbox Series controller

### ESP32 chip

None, Raspberry Pi pico W

### OS

Linux

### Relevant log output

```shell
(0x20006644) dpad=0x00, x= -54, y=  79, rx=   0, ry=   0, brake=   0, throttle=   0, buttons=0x0000, misc=0x00, gyro= 176000, -39000, 120000 accel=    535,  -3105,  -2859, batte5
id: 0
(0x20006644) dpad=0x00, x= -54, y=  78, rx=   0, ry=   0, brake=   0, throttle=   0, buttons=0x0000, misc=0x00, gyro=-417000,-112000, -48000 accel=    611,  -3131,  -2622, batte5
id: 0
(0x200039bc) dpad=0x02, x= -15, y= -23, rx=  -4, ry=   7, brake=   0, throttle=   0, buttons=0x0000, misc=0x00, gyro=      0,      0,      0 accel=      0,      0,      0, batte0
id: 0
(0x200039bc) dpad=0x00, x= -15, y= -23, rx=  -4, ry=   7, brake=   0, throttle=   0, buttons=0x0000, misc=0x00, gyro=      0,      0,      0 accel=      0,      0,      0, batte0
id: 0
```

### Relevant sketch

- Use example for pico w platform on latest commit of `develop branch`.
- Change code of `static void my_platform_on_controller_data(uni_hid_device_t* d, uni_controller_t* ctl)`, add the following two lines at the beginning:
```c
static void my_platform_on_controller_data(uni_hid_device_t* d, uni_controller_t* ctl) {
    int id = uni_hid_device_get_idx_for_instance(d);
    logi("id %d ", idx);
    ...
```
- Compile and flash program, output should only net id of value `0`.

**Comment by ricardoquesada** [comment]
your sketch is incomplete... how are you printing `idx` ?

**Comment by ricardoquesada** [comment]
also, you should check return value... if it `idx < 0` it is an error

**Comment by juan518munoz** [comment]
Sorry, I was working with two code editors side by side and passed the wrong one, it's now updated.

I never got a `-1` signaling an error.

**Comment by ricardoquesada** [comment]
again, your sketch is incomplete.
I strongly suggest that you paste a complete sketch... something that compiles and reproduce the error. don't just copy & paste parts of it. 

for example, I don't know what  `get_connected_device_idx()`  is.

**Comment by juan518munoz** [comment]
Sent the wrong snipped again, sorry, It was late and instead of focusing on what I was doing, I wanted to get it done. I've updated the sketch. Please let me know if something else is needed.
