### ISSUE TITLE
Add Bluepad32 to Board Manager

### ISSUE THREAD

**Issue by JB7567** [ricardoquesada/bluepad32#64]
Hello!
After adding the URL under Preferences - Additional Board Managers URLs, I get an error when I press install on the esp32_bluepad32 manager in the Boards Manager window.

Failed to install platform: 'esp32-bluepad32:esp32:3.10.2'.
Error: 9 FAILED_PRECONDITION: Platform 'esp32-bluepad32:esp32@3.10.2' not found: getting tool dependencies for platform esp32-bluepad32:esp32@3.10.2: tool version v0.12.0-esp32-20230419 not found

![2024-01-25 09_18_21-sketch_jan25a _ Arduino IDE 2 2 1](https://github.com/ricardoquesada/bluepad32/assets/69703036/e95c89b4-cffc-4176-bb58-8b2429491752)

**Comment by ricardoquesada** [comment]
Install "ESP32 2.0.14" ... that might solve the precondition error
