### ISSUE TITLE
Arduino Nano ESP32 / Lolin S3 mini: Serial output not working

### ISSUE THREAD

**Issue by lp524** [ricardoquesada/bluepad32#84]
Hello Im still having trouble getting my Arduino Nano ESP32 to work with my xbox controller. after making the changes in issue #65 I still get the following error when trying to upload.
No DFU capable USB device available
Failed uploading: uploading error: exit status 74
It also seems to think the arduino is a LOLIN S3 still
If you could help that would be great.

**Comment by ricardoquesada** [comment]
Sorry, but I cannot help you with that. I wouldn't know...
have you Googled that error message ? I guess you'll find some kind of answer on the Arduino forums.

**Comment by lp524** [comment]
> Sorry, but I cannot help you with that. I wouldn't know... have you Googled that error message ? I guess you'll find some kind of answer on the Arduino forums.

Ok thank you but I believe it is an error in your code recognizing the Adruino Nano ESP 32

**Comment by ricardoquesada** [comment]
https://letmegooglethat.com/?q=arduino+nano+esp32+%22No+DFU+capable+USB+device+available+Failed+uploading%3A+uploading+error%3A+exit+status+74%22&l=1
