### ISSUE TITLE
[Bug]: Warning message when Gamesir T3s connects

### ISSUE THREAD

**Issue by FrankMeck** [ricardoquesada/bluepad32#94]
### What happened?

The serial monitor displays the following when a Gamezsir T3s is connected:
     Switch: invalid spi factory stick calibration len; got 25, wanted 18
     Switch: Error, unexpected subcmd_id=0x00 in report 0x21
I just noticed this error after updating  

### Bluepad32 Version

4.0-beta2

### Bluepad32 version custom

Version appears to be 4.0.2 from the 'include' paths in VS Code. It was recently updated by the Arduino IDE. I normally use VS Code, but use the Arduino IDE occasionally.

### Bluepad32 Platform

Other

### Platform version

VS Code

### Controller

Gamesir T3s

### Microcontroller

ESP32

### Microcontroller board

ESP-WROOM-32D on custom PCB.

### OS

Windows

**Comment by ricardoquesada** [comment]
This is what GameSir T3s reports for calibration:
`C8 85 61 E4 D7 7D 69 66 5C 4A 08 78 41 66 58 6A B5 62 FF 32 32 32 FF FF FF`

which looks valid expect for the extra 7 bytes... so we are going to fix this by accepting reports that are longer than needed.
